#!/bin/sh
### BEGIN INIT INFO
# Provides:          go_app
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: golang-app Service
# Description:       Start/stop golang-app API service
### END INIT INFO

# mv go_app /etc/init.d/
# service go_app start

DAEMON=/root/project/golang-app/bin/main
DAEMON_DIR=/root/project/golang-app
DAEMON_NAME=apistore
PIDFILE=/var/run/$DAEMON_NAME.pid
USER=root

. /lib/lsb/init-functions

start() {
    log_daemon_msg "Starting $DAEMON_NAME"
    start-stop-daemon --start --quiet --chdir $DAEMON_DIR --background \
        --make-pidfile --pidfile $PIDFILE --exec $DAEMON
    log_end_msg $?
}

stop() {
    log_daemon_msg "Stopping $DAEMON_NAME"
    start-stop-daemon --stop --quiet --pidfile $PIDFILE --retry 10
    rm -f $PIDFILE
    log_end_msg $?
}

status() {
    status_of_proc -p $PIDFILE $DAEMON $DAEMON_NAME && exit 0 || exit $?
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0

